# Generated by Django 4.0.4 on 2023-03-04 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tempSignin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 17, 23, 52, 644130, tzinfo=utc)),
        ),
    ]
