# Generated by Django 4.0.4 on 2023-03-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.category",
            ),
            preserve_default=False,
        ),
    ]
